core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .apps import CoreConfig
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.home, name='dashboard'),

    path('company/add/', view=views.company_create, name='company-add'),
    path('company/delete/<uuid:pk>/', view=views.company_delete, name='company-delete'),
    path('company/detail/<uuid:pk>/', view=views.company_detail, name='company-detail'),
    path('company/edit/<uuid:pk>/', view=views.company_update, name='company-edit'),
    path('company/list/', view=views.company_list, name='company-list'),

]

etesting/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('', include('core.urls')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('api/core/', include('core_api.urls')),
    path('api/schema/', get_schema_view(title="{} API".format("SavvyBiz Test"))),
    path('api/docs/', include_docs_urls(title="{} API".format("SavvyBiz Test"))),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
import logging

from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import ProgrammingError
from django.forms import modelformset_factory
from django.utils.safestring import mark_safe

from core.models import Timezone, Company, Address

log = logging.getLogger("{}.*".format(__package__))
log.setLevel(settings.LOGGING_LEVEL)

UserModel = get_user_model()


class StampedUpdaterModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(StampedUpdaterModelForm, self).__init__(*args, **kwargs)  # populates the post

        if self.fields.get("updated_by", False):
            del self.fields["updated_by"]


class TrackedModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(TrackedModelForm, self).__init__(*args, **kwargs)  # populates the post

        if self.fields.get("company", False):
            del self.fields["company"]

        if self.fields.get("updated_by", False):
            del self.fields["updated_by"]


class AddressForm(TrackedModelForm):

    # def __init__(self, *args, **kwargs):
    #     self.readonly = kwargs.pop('readonly', False)
    #     self.types = kwargs.pop('types', None)

    class Meta:
        model = Address
        # fields = '__all__'
        exclude = ('country', 'enabled')

        widgets = {
            'state': forms.Select(attrs={'class': 'form-control select2', 'data-type': 'select2'}),
            'type': forms.Select(attrs={'class': 'form-control select2', 'data-type': 'select2'}),
        }


try:
    AddressFormSet = modelformset_factory(Address, form=AddressForm, extra=1, max_num=len(Address.OFFICIAL_TYPE) - 1,
                                          can_delete=True)
except ProgrammingError:
    AddressFormSet = modelformset_factory(Address, form=AddressForm, extra=1, max_num=0, can_delete=True)


class CompanyForm(StampedUpdaterModelForm):

    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)  # populates the post

        self.fields['timezone'].queryset = Timezone.objects.filter(enabled=True)
        self.fields['timezone'].label = "Time Zone"

    class Meta:
        model = Company
        fields = '__all__'
        exclude = ('addresses', 'alias', 'enabled',)

        widgets = {
            'timezone': forms.Select(attrs={'class': 'form-control select2'}),
            'status': forms.Select(attrs={'class': 'form-control select2'}),
            'state': forms.Select(attrs={'class': 'form-control select2'}),
            # 'about': forms.Textarea(attrs={'rows': 2}),
            # 'note': forms.Textarea(attrs={'rows': 2}),
        }

core/views.py
import json
import logging

from django.conf import settings
from django.contrib import messages, auth
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.db import transaction, IntegrityError
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from core.forms import CompanyForm, AddressFormSet
from core.models import Company, Address

log = logging.getLogger("{}.*".format(__package__))
log.setLevel(settings.LOGGING_LEVEL)

UserModel = get_user_model()
TITLE_SUCCESS = "Success Response!!!"
TITLE_ERROR = "Error Response!!!"
DUPLICATE_ERROR = "Attempt to create a duplicate entry for '{}' has been averted"
FORM_ERROR = "Please check you have filled the form correctly"
INVALD_TIMEZONE_WARNING = "Your profile have invalid Timezone and this may result to inconsistent datetime"

ADDED_SUCCESS = "{} ({}) successfully added"
CREATE_SUCCESS = "{} ({}) successfully created"
UPDATE_SUCCESS = "{} <i>({})</i> successfully updated"
DELETE_SUCCESS = "{} ({}) successfully deleted"

TYPE_INFO = "info"
TYPE_SUCCESS = "success"
TYPE_ERROR = "error"


def index(request):
    # On Completion submit to our Lead Developer Paul Via Sk ype @pauldiconline
    if request.user.is_authenticated:
        return redirect(reverse("core:dashboard"))
    return render(request, "core/home.html", context={})


@login_required
def home(request):
    context = {}
    # On Completion submit to our Lead Developer Paul Via Sk ype @pauldiconline
    return render(request, "core/dashboard.html", context=context)


def error_403(request, exception):
    """
    Page not found Error 404
    """

    return render(request, 'core/403.html', context={})


def error_404(request, exception):
    log.error("****** 404")
    return render(request, 'core/404.html', context={})


def error_500(request):
    log.error("****** 500")
    return render(request, 'core/500.html', context={})


@login_required
def company_create(request, item=None):
    if request.method == "POST":
        company_form = CompanyForm(request.POST, prefix='company', request=request, instance=item)
        address_formset = AddressFormSet(request.POST, prefix='address',
                                         queryset=item.addresses.all() if item else Address.objects.none())

        if company_form.is_valid() and address_formset.is_valid():
            with transaction.atomic():
                company = company_form.save(commit=False)
                company.update_tracked(auth.get_user(request))
                addresses = address_formset.save(commit=False)
                try:
                    company.save()

                    for address in addresses:
                        address.update_tracked(auth.get_user(request))
                        address.save()

                    company.addresses.set(addresses)
                except IntegrityError as err:
                    log.error(err)
                    ok = False
                    transaction.set_rollback(rollback=True)
                    msg = "Sorry, alias '{}' not allowed".format("...")
                    if request.is_ajax():
                        return JsonResponse({"msg": msg, "type": FORM_ERROR, "data": {"pk": company_form.instance.pk}}, safe=True)
                    else:
                        messages.warning(request, msg)

                # company_form.save_m2m()

                msg = UPDATE_SUCCESS.format(company._meta.verbose_name, company) if item else CREATE_SUCCESS.format(company._meta.verbose_name, company)
                if request.is_ajax():
                    return JsonResponse({"msg": msg, "type": TYPE_SUCCESS, "data": {"pk": company_form.instance.pk}}, safe=True)
                else:
                    messages.success(request, msg, TITLE_SUCCESS)
                    return redirect(company_form.instance.get_absolute_url())
        else:
            logging.warning(json.dumps(company_form.errors))
            logging.warning(json.dumps(address_formset.errors))
            if request.is_ajax():
                data = {**json.dumps(company_form.errors), **json.dumps(address_formset.errors)}
                return JsonResponse({"msg": FORM_ERROR, "type": TYPE_INFO, "data": data}, safe=True)
            else:
                messages.warning(request, FORM_ERROR, TITLE_ERROR)
    else:
        company_form = CompanyForm(prefix='company', request=request, instance=item)
        address_formset = AddressFormSet(prefix='address', queryset=item.addresses.all() if item else Address.objects.none())

    template = "core/company-form.html" if request.is_ajax() else "core/company-add.html"
    context = {'company_form': company_form, 'address_formset': address_formset}

    return render(request, template, context=context)


@login_required
def company_update(request, pk):
    company = get_object_or_404(Company, pk=pk)
    if request.method == "POST" and request.is_ajax() and request.POST.get("level_0_limit", False):
        company.save()
        return JsonResponse({"msg": "Email Timeout Limits Updated", "type": TYPE_SUCCESS, "data": {}}, safe=True)

    return company_create(request, company)


@login_required
def company_list(request):
    items = Company.objects.all()
    return render(request, "core/company-list.html", context={"items": items})


@login_required
def company_detail(request, pk):
    instance = Company.objects.get(pk=pk)

    return render(request, "core/company-add.html", context={"instance": instance, "domain": get_current_site(request)})


@login_required
def company_delete(request, pk):
    item = get_object_or_404(Company, pk=pk)
    msg = DELETE_SUCCESS.format(item._meta.verbose_name, item)
    item.delete()

    if request.is_ajax():
        return JsonResponse({"msg": msg, "type": TYPE_SUCCESS}, safe=True)
    else:
        messages.warning(request, msg, TITLE_SUCCESS)
    return redirect(Company.get_list_url())

core/templates/core/base_error.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>403 Error - Lost page</title>
    <meta charset="utf-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
    <meta content="SavvyBizs" name="keywords">
    <meta content="Express Expand" name="author">
    <meta content="SavvyBiz Dashboard" name="description">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="favicon.png" rel="shortcut icon">
    <link href="apple-touch-icon.png" rel="apple-touch-icon">
    <link href="//fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet" type="text/css">
    <link href="{% static 'perfect-scrollbar/css/perfect-scrollbar.min.css' %}" rel="stylesheet">
    <link href="{% static 'slick-carousel/slick/slick.css' %}" rel="stylesheet">


    <link href="{% static 'select2/dist/css/select2.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
    <link href="{% static 'dropzone/dist/dropzone.css' %}" rel="stylesheet">
    <link href="{% static 'datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'fullcalendar/dist/fullcalendar.min.css' %}" rel="stylesheet">
    <link href="{% static 'perfect-scrollbar/css/perfect-scrollbar.min.css' %}" rel="stylesheet">
    <link href="{% static 'slick-carousel/slick/slick.css' %}" rel="stylesheet">

    <link href="{% static 'css/main.css' %}" rel="stylesheet">
  </head>

<body class="content-box full-screen">
    {% block contents %}
    {% endblock %}
</body>
</html>

core/templates/core/company-add.html
{% extends 'core/base.html' %}

{% load static bootstrap4 %}

{% block contents %}

    <div class="content-box">
        <div class="element-wrapper">
            <div class="element-box col">
                <h5 class="form-header">
                {% if company_form %}
                    {% if company_form.instance.created %}
                        <i class="fal fa-pencil-alt"></i> Edit Company
                    {% else %}
                        <i class="fal fa-layer-plus"></i> New Company
                    {% endif %}
                {% elif instance.created %}
                    <i class="fa fa-id-card-o"></i> View Companies
                {% endif %}

                <small>
                    <a href="{% url 'core:company-list' %}" title="View Companies" data-toggle='tooltip' class="float-right"><i class="fal fa-list"></i> Companies</a>
                </small>
                </h5>
                <div class="form-desc"></div>

                <div class="row justify-content-md-center">
                    <div class="col-12 col-sm-11">
                        {% if company_form %}
                            {% include 'core/company-form.html' %}
                        {% elif instance.created %}
                            {% include 'core/company-detail.html' %}
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
             $("#top-save-button").click(function () {
                 $("#company-form").submit()
             });
        });
    </script>
{% endblock %}


core/templates/core/company-detail.html
{% load static tz %}

<div class="row">
    <div class="element-wrapper">
        <div class="element-box"><h6 class="element-header">{{ instance.name }}</h6>
            <div class="timed-activities compact">
                <div class="timed-activity">
                    <div class="ta-date"><span>{{ instance.phone }} / {{ instance.email }}</span></div>
                    <div class="ta-record-w">
                        <div class="ta-record">
                            <div class="ta-timestamp"><strong>Website</strong></div>
                            <div class="ta-activity">{{ instance.website|default:"" }}</div>
                        </div>
                        <div class="ta-record">
                            <div class="ta-timestamp"><strong>Facebook</strong></div>
                            <div class="ta-activity">{{ instance.facebook|default:"" }}</div>
                        </div>
                        <div class="ta-record">
                            <div class="ta-timestamp"><strong>Twitter</strong></div>
                            <div class="ta-activity">{{ instance.twitter|default:"" }}</div>
                        </div>
                        <div class="ta-record">
                            <div class="ta-timestamp"><strong>Linkedin</strong></div>
                            <div class="ta-activity">{{ instance.linkedin|default:"" }}</div>
                        </div>
                        <div class="ta-record">
                            <div class="ta-timestamp"><strong>Instagram</strong></div>
                            <div class="ta-activity">{{ instance.instagram|default:"" }}</div>
                        </div>
                        <div class="ta-record">
                            <div class="ta-timestamp"><strong>Youtube</strong></div>
                            <div class="ta-activity">{{ instance.youtube|default:"" }}</div>
                        </div>
                        <div class="ta-record">
                            <div class="ta-timestamp"><strong>Timezone</strong></div>
                            <div class="ta-activity">{{ instance.timezone|default:"" }}</div>
                        </div>
                        <div class="ta-record">
                            <div class="ta-timestamp"><strong>Status</strong></div>
                            <div class="ta-activity">{{ instance.status|default:"" }}</div>
                        </div>
                        <div class="ta-record">
                            <div class="ta-timestamp"><strong>Website</strong></div>
                            <div class="ta-activity">{{ instance.website|default:"" }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="element-wrapper">
        <div class="element-box"><h6 class="element-header">{{ instance.name }} Addresses</h6>
            <div class="timed-activities compact">
                {% for add in instance.addresses.all %}
                    <div class="timed-activity">
                        <div class="ta-date"><span class="{% if add.default %}text-success{% endif %}">{{ add.line_1 }} ({{ add.type }})</span></div>
                        <div class="ta-record-w">
                            <div class="ta-record">
                                <div class="ta-timestamp"><strong>{{ add.line_1 }} {{ add.line_2|default:'' }} <br>{{ add.city }} {{ add.zip }} {{ add.state }}<br>{{ add.country }} </strong></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

core/templates/core/company-form.html
{% load bootstrap4 static tz i18n %}
{% block contents %}
    <style>
        .alert.alert-danger.alert-dismissable.alert-link{
            display: none;
        }
    </style>
    <div class="content-box">
        <form method="POST" id="company-form" novalidate>
            {% csrf_token %}
            <div class="row">
                {% bootstrap_form company_form form_group_class="form-group col-12 col-sm-6" %}
            </div>

            {{ address_formset.management_form }}

            <div class="row" data-form-list="{{ address_formset.prefix }}-prefix">
                {% for address_form in address_formset %}
                    <div id="{{ address_form.prefix }}-row" class="dynamic-form row mt-2 form-buttons-w">
                        <div class="col-12">
                            <span class="d-none">
                                {{ address_form.DELETE }}
                                {% if address_form.instance %}{{ address_form.id }}{% endif %}
                            </span>
                            <a id="remove-{{ address_form.prefix }}-row" href="javascript:void(0)" data-prefix="{{ address_formset.prefix }}" title="Remove Current {{ address_form.type.label }}" class="delete-row float-right mx-1 {% if forloop.first %}d-none{% endif %}">
                                <i class="os-icon os-icon-cancel-circle text-danger"></i>
                            </a>

                            <a class="float-right add-row {% if not forloop.first %}d-none{% endif %}" data-prefix="{{ address_formset.prefix }}" title="Add New {{ address_form.type.label }}">
                                <i class="os-icon os-icon-coins-4 mx-1 text-primary"></i>
                            </a>
                        </div>

                        {% bootstrap_form address_form exclude="DELETE" form_group_class="form-group col-12 col-sm-6" %}
                    </div>
                {% endfor %}

                <button class="btn btn-primary float-right"><i class="far fa-check-double"></i> Submit Form</button>
            </div>
        </form>
    </div>
{% endblock %}

<script src="{% static 'js/dynamic-formset.js' %}"></script>
<link href="{% static 'select2/dist/css/select2.min.css' %}" rel="stylesheet">
<script src="{% static 'select2/dist/js/select2.full.min.js' %}"></script>

<script>
    $(document).ready(function () {
        $(".select2").select2()
        {% if request.is_ajax %}
            $("#company-form input[type='submit']").click(function (ev) {
                ev.preventDefault();
                var selector = "#id_company";
                {% if form.instance.created %}
                    var url = "{% url 'core:company-edit' form.instance.pk %}";
                {% else %}
                    var url = "{% url 'core:company-add' %}";
                {% endif %}

                processFeed(url, $("#company-form").serialize(), "Processing your request...", "POST", function (d) {
                    if (d.type == "success") {
                        BootstrapDialog.show({
                            message: d.msg,
                            onhide: function (bdialog) {
                                if (typeof bdialog !== null && typeof bdialog !== "undefined") {
                                    bdialog.close();
                                }
                            }
                        });
                    } else {
                        renderError($("#company-form"), d.data)
                        pwd(d.msg, false, true)
                    }
                }, function (d) {
                    BootstrapDialog.show({message: d.responseText});
                });
            });

        {% endif %}
    });

    function before_clone(){
        {% if not is_mobile %}
            $("select[data-type='select2']").select2("destroy");
            $("select[data-type='select2'],select[data-type='select2'] option").removeAttr("data-select2-id");
        {% endif %}
    }

    function after_clone(){
        {% if not is_mobile %}
            $.each($("select[data-type='select2']"), function (i, v) {
                $(v).select2().data('select2').listeners['*'].push(function(name, target) {
                    if(name == 'focus') {$(this.$element).select2("open");}
                });
            });
        {% endif %}
    }

</script>

core/templates/core/company-list.html
{% extends 'core/base.html' %}

{% load static %}

{% block contents %}
    <div class="content-box">
        <div class="element-wrapper">
            <div class="element-box">
                <h5 class="form-header">
                    <i class="fa fa-id-card-o"></i> Manage Companies
                    {% if not request.user.company and request.user.is_staff %} <small><a href="{% url 'core:company-add' %}" title="Add New Company" data-toggle='tooltip' class="float-right"><i class="fal fa-layer-plus"></i> Add Company</a></small>{% endif %}
                    <!-- On Completion submit to our Lead Developer Paul Via Skype @pauldiconline-->
                </h5>
                <div class="table-responsive">
                    <table id="company-table" width="100%" class="table table-striped table-sm table-lightfont">
                        <thead>
                            <tr>
                                <th class="text-center">*</th>
                                <th>Status</th>
                                <th>Name</th>
                                <th>City</th>
                                <th>State</th>
                                <th>Phone</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in items %}
                                <tr>
                                    <td data-type="Status"><a href="{% url 'core:company-edit' item.pk %}" title="Edit {{ item.name }}" data-toggle="tooltip"><i class="os-icon os-icon-pencil-1"></i> </a></td>
                                    <td class="px-0 text-center"><a href="{% url 'core:company-detail' item.pk %}" title="View {{ item.name }}" data-toggle="tooltip">{{ item }}</a></td>
                                    <td data-type="Status">{{ item.status }} </td>
                                    <td data-type="Name">
                                        {% if company == item %}
                                            <a href="javascript:;" title='Stop impersonating {{ item }}' data-toggle='tooltip' class="impersonate text-danger" data-company="Savvy Biz"><i class="far fa-person-carry mr-2"></i></a>
                                            <b>{{ item}}</b>
                                        {% else %}
                                            <a href="javascript:;" title='Start impersonating {{ item }}' data-toggle='tooltip' class="impersonate text-primary" data-company="{{ item }}"><i class="fas fa-person-carry mr-2"></i></a>
                                            {{ item }}
                                        {% endif %}

                                    </td>
                                    <td data-type="City">{{ item.address.city }}</td>
                                    <td data-type="State">{{ item.address.state }}</td>
                                    <td data-type="Phone">{{ item.phone }}</td>
                                </tr>
                            {%endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>

    <script src="{% static 'datatables/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'datatables/datatables/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'datatables/fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
{#    <script src="{% static 'datatables/select/js/s' %}"></script>#}
    <script>
        $(document).ready(function () {
            $(".impersonate").click(function () {
                processFeed($(this).data('url'), {}, "Updating your entity Company to "+$(this).data('company'), 'post', function(d){
                    toastr["success"](d.msg);
                    location.href = "."
                }, function(d){
                    toastr["error"](d.responseText);
                });
            });

            var table = $('#company-table').DataTable( {
	            stateSave: true,
                {#pagingType: "full_numbers",#}
                paging:   false,
                fixedHeader: true,
                select: true,
                fixedColumns:   {
                    leftColumns: 2
                },
                {#aoColumnDefs: [{#}
                {#    'bSortable': false,#}
                {#    'aTargets': [1]#}
                {# }]#}

            } );

            function format(value) {
                var html = "";

                return '<div class="profile-tile"><div class="profile-tile-meta"><ul><li>:<strong>Online Now</strong></li><li>Tickets:<strong><a href="apps_support_index.html">12</a></strong></li><li>Response Time:<strong>2 hours</strong></li></ul><div class="pt-btn"></div></div></div>'




                {#$.each(value, function (i, v) {#}
                {#    if (i!=0){#}
                {#        html += v + "<br>";#}
                {#    }#}
                {##}
                {# });#}
                {#return '<div>' + html + '</div>';#}
            }

            $('#company-table tbody').on('click', 'td.details-control', function () {
                console.log(table.rows().data());
                var tr = $(this).closest('tr');
                console.log(table.rows().data()[tr.index()]);
                var row = table.row(tr);
                console.log(row);

                if (row.child.isShown()) {
                    // This row is already open - close it
                    row.child.hide();
                    tr.removeClass('shown');
                } else {
                    // Open this row
                    row.child(format(row.data())).show();
                    tr.addClass('shown');
                }
            });

            // Add event listener for opening and closing details
            $('#company-table tbody_').on('click', 'td.details-control', function () {
                var tr = $(this).closest('tr');
                var row = table.row(tr);
                if (row.child.isShown()) {
                    // This row is already open - close it
                    row.child(format(tr.data('child-name'), tr.data('child-value'))).hide();
                    tr.removeClass('shown');
                }
                else {
                    // Open this row
                    row.child(format(tr.data('child-name'), tr.data('child-value'))).show();
                    tr.addClass('shown');
                }
            });

        });
    </script>
{% endblock %}

core/templates/core/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% block contents %}

    <div class="content-box">
        <div class="row">
            <h3 class="col-12">Welcome to SavvyBiz Practical Test</h3>
            <div class="col-12">
                <strong>Objectives:</strong>
                <p>You are required to prove your ability do ReactJS on Django (Testing is a plus).
                    Having the ability to do Test Driven Development with optimal coverage will be an added advantage </p>

                <strong>Task:</strong>
                <p>This project uses Django forms and Django default templates to create, edit and view Company and Company is a model defined in the core app.<br>
                    You are required to implement ReactJS equivalent of the current Django templates retaining all the functionalities that currently exists.
                    <i>It will be a plus to have TDD </i></p>

            </div>

            <p></p>
        </div>
    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block contents %}
        <div class="container text-center mt-5">
            <h1>HOME PAGE</h1>
            <h2><i class="far fa-exclamation-triangle text-warning fa-2x"></i> Provide default Content for Unauthenticated Users</h2>
        </div>
{% endblock %}