core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .apps import CoreConfig
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.home, name='dashboard'),

    path('company/add/', view=views.company_create, name='company-add'),
    path('company/delete/<uuid:pk>/', view=views.company_delete, name='company-delete'),
    path('company/detail/<uuid:pk>/', view=views.company_detail, name='company-detail'),
    path('company/edit/<uuid:pk>/', view=views.company_update, name='company-edit'),
    path('company/list/', view=views.company_list, name='company-list'),

]

etesting/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('', include('core.urls')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('api/core/', include('core_api.urls')),
    path('api/schema/', get_schema_view(title="{} API".format("SavvyBiz Test"))),
    path('api/docs/', include_docs_urls(title="{} API".format("SavvyBiz Test"))),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
import logging

from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import ProgrammingError
from django.forms import modelformset_factory
from django.utils.safestring import mark_safe

from core.models import Timezone, Company, Address

log = logging.getLogger("{}.*".format(__package__))
log.setLevel(settings.LOGGING_LEVEL)

UserModel = get_user_model()


class StampedUpdaterModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(StampedUpdaterModelForm, self).__init__(*args, **kwargs)  # populates the post

        if self.fields.get("updated_by", False):
            del self.fields["updated_by"]


class TrackedModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(TrackedModelForm, self).__init__(*args, **kwargs)  # populates the post

        if self.fields.get("company", False):
            del self.fields["company"]

        if self.fields.get("updated_by", False):
            del self.fields["updated_by"]


class AddressForm(TrackedModelForm):

    # def __init__(self, *args, **kwargs):
    #     self.readonly = kwargs.pop('readonly', False)
    #     self.types = kwargs.pop('types', None)

    class Meta:
        model = Address
        # fields = '__all__'
        exclude = ('country', 'enabled')

        widgets = {
            'state': forms.Select(attrs={'class': 'form-control select2', 'data-type': 'select2'}),
            'type': forms.Select(attrs={'class': 'form-control select2', 'data-type': 'select2'}),
        }


try:
    AddressFormSet = modelformset_factory(Address, form=AddressForm, extra=1, max_num=len(Address.OFFICIAL_TYPE) - 1,
                                          can_delete=True)
except ProgrammingError:
    AddressFormSet = modelformset_factory(Address, form=AddressForm, extra=1, max_num=0, can_delete=True)


class CompanyForm(StampedUpdaterModelForm):

    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)  # populates the post

        self.fields['timezone'].queryset = Timezone.objects.filter(enabled=True)
        self.fields['timezone'].label = "Time Zone"

    class Meta:
        model = Company
        fields = '__all__'
        exclude = ('addresses', 'alias', 'enabled',)

        widgets = {
            'timezone': forms.Select(attrs={'class': 'form-control select2'}),
            'status': forms.Select(attrs={'class': 'form-control select2'}),
            'state': forms.Select(attrs={'class': 'form-control select2'}),
            # 'about': forms.Textarea(attrs={'rows': 2}),
            # 'note': forms.Textarea(attrs={'rows': 2}),
        }

core/views.py
import json
import logging

from django.conf import settings
from django.contrib import messages, auth
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.db import transaction, IntegrityError
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from core.forms import CompanyForm, AddressFormSet
from core.models import Company, Address

log = logging.getLogger("{}.*".format(__package__))
log.setLevel(settings.LOGGING_LEVEL)

UserModel = get_user_model()
TITLE_SUCCESS = "Success Response!!!"
TITLE_ERROR = "Error Response!!!"
DUPLICATE_ERROR = "Attempt to create a duplicate entry for '{}' has been averted"
FORM_ERROR = "Please check you have filled the form correctly"
INVALD_TIMEZONE_WARNING = "Your profile have invalid Timezone and this may result to inconsistent datetime"

ADDED_SUCCESS = "{} ({}) successfully added"
CREATE_SUCCESS = "{} ({}) successfully created"
UPDATE_SUCCESS = "{} <i>({})</i> successfully updated"
DELETE_SUCCESS = "{} ({}) successfully deleted"

TYPE_INFO = "info"
TYPE_SUCCESS = "success"
TYPE_ERROR = "error"


def index(request):
    # On Completion submit to our Lead Developer Paul Via Sk ype @pauldiconline
    if request.user.is_authenticated:
        return redirect(reverse("core:dashboard"))
    return render(request, "core/home.html", context={})


@login_required
def home(request):
    context = {}
    # On Completion submit to our Lead Developer Paul Via Sk ype @pauldiconline
    return render(request, "core/dashboard.html", context=context)


def error_403(request, exception):
    """
    Page not found Error 404
    """

    return render(request, 'core/403.html', context={})


def error_404(request, exception):
    log.error("****** 404")
    return render(request, 'core/404.html', context={})


def error_500(request):
    log.error("****** 500")
    return render(request, 'core/500.html', context={})


@login_required
def company_create(request, item=None):
    if request.method == "POST":
        company_form = CompanyForm(request.POST, prefix='company', request=request, instance=item)
        address_formset = AddressFormSet(request.POST, prefix='address',
                                         queryset=item.addresses.all() if item else Address.objects.none())

        if company_form.is_valid() and address_formset.is_valid():
            with transaction.atomic():
                company = company_form.save(commit=False)
                company.update_tracked(auth.get_user(request))
                addresses = address_formset.save(commit=False)
                try:
                    company.save()

                    for address in addresses:
                        address.update_tracked(auth.get_user(request))
                        address.save()

                    company.addresses.set(addresses)
                except IntegrityError as err:
                    log.error(err)
                    ok = False
                    transaction.set_rollback(rollback=True)
                    msg = "Sorry, alias '{}' not allowed".format("...")
                    if request.is_ajax():
                        return JsonResponse({"msg": msg, "type": FORM_ERROR, "data": {"pk": company_form.instance.pk}}, safe=True)
                    else:
                        messages.warning(request, msg)

                # company_form.save_m2m()

                msg = UPDATE_SUCCESS.format(company._meta.verbose_name, company) if item else CREATE_SUCCESS.format(company._meta.verbose_name, company)
                if request.is_ajax():
                    return JsonResponse({"msg": msg, "type": TYPE_SUCCESS, "data": {"pk": company_form.instance.pk}}, safe=True)
                else:
                    messages.success(request, msg, TITLE_SUCCESS)
                    return redirect(company_form.instance.get_absolute_url())
        else:
            logging.warning(json.dumps(company_form.errors))
            logging.warning(json.dumps(address_formset.errors))
            if request.is_ajax():
                data = {**json.dumps(company_form.errors), **json.dumps(address_formset.errors)}
                return JsonResponse({"msg": FORM_ERROR, "type": TYPE_INFO, "data": data}, safe=True)
            else:
                messages.warning(request, FORM_ERROR, TITLE_ERROR)
    else:
        company_form = CompanyForm(prefix='company', request=request, instance=item)
        address_formset = AddressFormSet(prefix='address', queryset=item.addresses.all() if item else Address.objects.none())

    template = "core/company-form.html" if request.is_ajax() else "core/company-add.html"
    context = {'company_form': company_form, 'address_formset': address_formset}

    return render(request, template, context=context)


@login_required
def company_update(request, pk):
    company = get_object_or_404(Company, pk=pk)
    if request.method == "POST" and request.is_ajax() and request.POST.get("level_0_limit", False):
        company.save()
        return JsonResponse({"msg": "Email Timeout Limits Updated", "type": TYPE_SUCCESS, "data": {}}, safe=True)

    return company_create(request, company)


@login_required
def company_list(request):
    items = Company.objects.all()
    return render(request, "core/company-list.html", context={"items": items})


@login_required
def company_detail(request, pk):
    instance = Company.objects.get(pk=pk)

    return render(request, "core/company-add.html", context={"instance": instance, "domain": get_current_site(request)})


@login_required
def company_delete(request, pk):
    item = get_object_or_404(Company, pk=pk)
    msg = DELETE_SUCCESS.format(item._meta.verbose_name, item)
    item.delete()

    if request.is_ajax():
        return JsonResponse({"msg": msg, "type": TYPE_SUCCESS}, safe=True)
    else:
        messages.warning(request, msg, TITLE_SUCCESS)
    return redirect(Company.get_list_url())

core/templates/core/includes/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

core/templates/core/includes/header-menu.html
{% load static %}

<!--------------------
START - Top Bar
-------------------->
<div class="top-bar color-scheme-bright">
    <div class="top-icon top-settings " id="top-settings">
        <i class="far fa-align-justify"></i>
{#        {{ request.user.fullname }}:::{{ request.user.first_name }}:::{{ request.user.last_name }}:::{{ request.user.email }}#}

    </div>
    {% if request.user.is_staff %}
        <div class="top-icon top-id">
        {% if request.user.company.pk %}
            <a href="javascript:;" title="Change Company" data-target="#emulateCompany" data-toggle="modal">For {{ request.user.company }}</a>
            <a href="{% url 'core:update-assumed-company' 'aaaa0000-bb11-cc22-dd33-eeeeee555555' %}?url={{ request.get_full_path }}" title="Stop working as {{ request.user.company }}" data-toggle="tooltip" style="color: red"><i class="far fa-stop-circle"></i></a>
        {% else %}
            <a href="javascript:;" data-target="#emulateCompany" data-toggle="modal"><i class="fal fa-folders"></i></a>
        {% endif %}
        </div>

{#        <div class="top-icon top-id">#}
{#            <select name="assumed_company" id="id_assumed_company" class="select2">#}
{#                {% for c in request.user.companies %}#}
{#                    <option value="{{ c.0 }}" {% if c.0 == request.user.company.pk %}selected{% endif %}>{{ c.1 }}</option>#}
{#                {% endfor %}#}
{#            </select>#}
{#        </div>#}
    {% endif %}

    {% block drop_top_nav %}
    {% endblock %}

    <!--------------------
    START - Top Menu Controls
    -------------------->

    <div class="top-menu-controls">
{#        <div class="element-search autosuggest-search-activator">#}
{#            <input placeholder="Start typing to search..." type="text">#}
{#        </div>#}

        {% if request.user.is_authenticated %}
            <!-------------------
             START - Settings Link in secondary top menu
            -------------------->
            <div class="top-icon top-settings os-dropdown-trigger os-dropdown-position-left">
                <a href="{% url 'comm:follow-up-incoming' %}" class="text-white" title="New Incoming Communication" data-toggle="tooltip" data-placement="left"><i class="fas fa-comment-alt-plus"></i></a>
            </div>
{#            <div class="top-icon top-settings os-dropdown-trigger os-dropdown-position-left">#}
{#                <i class="fas fa-question-circle"></i>#}
{#                <div class="os-dropdown">#}
{#                    <div class="icon-w"><i class="fas fa-question-circle"></i></div>#}
{#                    <ul>#}
{#                        <li><a href="#"><i class="far fa-life-ring"></i><span>FAQ</span></a></li>#}
{#                        <li><a href="#"><i class="far fa-phone"></i><span>Contact Manager</span></a></li>#}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
            <div class="top-icon top-settings os-dropdown-trigger os-dropdown-position-left">
                <i class="far fa-alarm-clock"></i>
                <div class="os-dropdown">
                    <div class="icon-w"><i class="far fa-alarm-clock"></i></div>
                    <ul><li><a href="#"><i class="far fa-stopwatch"></i><span>Set Time</span></a></li></ul>
                </div>
            </div>

            <div class="top-icon top-settings os-dropdown-trigger os-dropdown-position-left">
                <i class="far fa-cog"></i>
                <div class="os-dropdown">
                    <div class="icon-w"><i class="far fa-cog"></i></div>
                    <ul>
                        {% if request.user.is_staff or request.user.is_superuser or request.user.is_manager %}
                            <li style="border-bottom: 1px solid rgba(255, 255, 255, 1);"><b>Add/Edit:</b></li>
                            <li><a href="{% url 'core:profile-list' %}">Users</a></li>
                            {% if request.user.is_staff or request.user.is_superuser %}
                                <li><a href="{% url 'core:company-list' %}">PM Company</a></li>
                            {% else %}
                                 <li><a href="{% url 'core:company-detail' request.user.company.pk %}">My Company</a></li>
                            {% endif %}
                            <li><a href="{% url 'core:department-list' %}">Department</a></li>
                            <li><a href="{% url 'core:portfolio-list' %}">Portfolio</a></li>
{#                            <li><a href="{% url 'core:owner-group-list' %}">Owner</a></li>#}
                            <li><a href="{% url 'core:building-list' %}">Building</a></li>
                            <li><a href="{% url 'core:unit-list' %}">Unit</a></li>
                            <li><a href="{% url 'contact:contract-list' %}">Transaction</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <!--------------------
            END - Settings Link in secondary top menu
            -------------------->
            <!--------------------
            START - User avatar and menu in secondary top menu
            -------------------->
            <div class="logged-user-w">
                <div class="logged-user-i">
                    <div class="avatar-w"><img alt="" src="{{ request.user.profile_pic_url }}" id="profile-picture-id" onerror="this.src='{% static 'img/default-profile-icon.png' %}'"></div>
                    <div class="logged-user-menu color-style-bright">
                        <div class="logged-user-avatar-info">
                            <div class="avatar-w">
                                {% if request.user.user_profile %}
                                    <a href="{% url 'core:profile-detail' request.user.user_profile.pk %}">
                                        <img alt="" src="{{ request.user.profile_pic_url }}">
                                    </a>
                                {% else %}
                                    <img alt="" src="{{ request.user.profile_pic_url }}">
                                {% endif %}
                            </div>
                            <div class="logged-user-info-w">
                                <div class="logged-user-name">
                                    {% if request.user.user_profile %}
                                        <a href="{% url 'core:profile-detail' request.user.user_profile.pk %}" class="text-white">{{ request.user.first_name|default:request.user.email|truncatechars_html:16 }}</a>
                                    {% else %}
                                        {{ request.user.first_name|default:request.user.email|truncatechars_html:16 }}
                                    {% endif %}
                                </div>
                                <div class="logged-user-role">
                                    {% if request.user.is_superuser %}
                                        ***SavvyBiz Admin
                                    {% elif request.user.is_staff %}
                                        SavvyBiz Admin
                                    {% elif False %}
                                        PM Admin
                                    {% else %}
                                        {{ request.user.first_name|default:request.user.email|truncatechars_html:16 }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="bg-icon">
                            <i class="os-icon os-icon-wallet-loaded"></i>
                        </div>
                        <ul>
                            <li><a href="apps_email.html"><i class="far fa-envelope"></i><span>Assigned Tickets</span></a></li>
                            {% if request.user.is_staff %}<li><a href="/access/" target="_blank"><i class="far fa-envelope"></i><span>Backend</span></a></li>{% endif %}
                            <li><a href="{% if request.user.user_profile %}{% url 'core:profile-detail' request.user.user_profile.pk %}{% else %}javascript:;{% endif %}"><i class="far fa-user-circle"></i><span>Profile Details</span></a></li>
                            <li><a href="users_profile_small.html"><i class="os-icon os-icon-coins-4"></i><span>Billing Details</span></a></li>
                            <li><a href="#"><i class="os-icon os-icon-others-43"></i><span>Notifications</span></a></li>
                            <li><a href="{% url 'account:logout' %}"><i class="os-icon os-icon-signs-11"></i><span>Logout</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--------------------
            END - User avatar and menu in secondary top menu
            -------------------->
        {% else %}
            <!--------------------
            START - User avatar and menu in secondary top menu
            -------------------->
            <div class="logged-user-w">
                <div class="logged-user-i">
                    <div class="avatar-w">
                        <img alt="" src="{% static 'img/anonnymous_icon.png' %}">
                    </div>
                    <div class="logged-user-menu color-style-bright">
                        <div class="logged-user-avatar-info">
                            <div class="avatar-w">
                                <img alt="" src="{% static 'img/anonnymous_icon.png' %}">
                            </div>
                            <div class="logged-user-info-w">
                                <div class="logged-user-name">Anonnymous</div>
                                <div class="logged-user-role">Anonnymous</div>
                            </div>
                        </div>
                        <div class="bg-icon"><i class="os-icon os-icon-wallet-loaded"></i></div>
                        <ul>
                            <li>
                                <a href="{% url 'account:login' %}"><i class="far fa-sign-in-alt"></i><span>Login</span></a>
                            </li>
                            <li>
                                <a href="{% url 'account:sign-up' %}"><i class="far fa-sign-out-alt"></i><span>Sign up</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--------------------
            END - User avatar and menu in secondary top menu
            -------------------->
        {% endif %}
    </div>
    <!--------------------
    END - Top Menu Controls
    -------------------->
</div>
<!--------------------
END - Top Bar
-------------------->

<script>
    $(function () {
        {#var image=document.getElementById("profile-picture-id").value;#}
        {#if(image==null || image==''){#}
            {#document.getElementById('profile-picture-id').setAttribute('src', "/static/img/default-profile-icon.png");#}
        {# }#}
        {#$("#profile-picture-id").each(function(i, v){#}
        {#    $(v).attr("onerror","this.src='/static/img/default-profile-icon.png'");#}
        {# });#}
    });
</script>

core/templates/core/includes/side-bar-left.html
{% load static %}

<!--------------------
START - Mobile Menu
-------------------->


<div class="menu-mobile menu-activated-on-click color-scheme-dark">
    <div class="mm-logo-buttons-w">
        <a class="mm-logo" href="{% url 'core:index' %}">
            <img src="{% static 'img/SavvyBiz-logo-Icon.png' %}"><span></span>
        </a>
        <div class="mm-buttons">
            <div class="content-panel-open">
                <div class="os-icon os-icon-grid-circles"></div>
            </div>
            <div class="mobile-menu-trigger">
                <div class="os-icon os-icon-hamburger-menu-1"></div>
            </div>
        </div>
    </div>


    <div class="menu-and-user">
        <div class="logged-user-w">
            <div class="avatar-w">
                <img alt="" src="{% static 'img/avatar1.jpg' %}">
            </div>
            <div class="logged-user-info-w">
                {% if request.user.is_authenticated %}
                    <div class="logged-user-name">{{ request.user.fullname }}</div>
                    <div class="logged-user-role">
                        {% if request.user.is_superuser %}
                            SB Administrator
                        {% elif request.user.is_staff %}
                            SB Staff
                        {% elif request.user.is_manager %}
                            PM Administrator
                        {% else %}
                            Member
                        {% endif %}
                    </div>
                {% else %}
                    <div class="logged-user-name">{{ request.user.fullname|default:"Annonymous" }}</div>
                    <div class="logged-user-role">{{ request.user.username|default:"Limit Account" }}</div>
                {% endif %}
            </div>
        </div>



        <!--------------------
        START - Mobile Menu List
        -------------------->
        {% if request.user.is_authenticated %}
            <ul class="main-menu">
                <li class="sub-menu">
                    <a href="{% url 'core:dashboard' %}">
                        <div class="icon-w"><div class="fas fa-home"></div></div>
                        <span>Home - Dashboard</span>
                    </a>
                </li>

                <li class="has-sub-menu">
                    <a href="javascript:;">
                        <div class="icon-w"><i class="fas fa-history"></i></div>
                        <span>Record Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="{% url 'record:index' %}">Find/Edit</a></li>
                        <li><a href="{% url 'record:record-add' %}">Add</a></li>
                        <li><a href="{% url 'record:record-list' %}">Reports</a></li>
                    </ul>
                </li>

                <li class="has-sub-menu">
                    <a href="{% url 'timer:index' %}">
                        <div class="icon-w"><i class="fas fa-alarm-clock"></i></div>
                        <span>Time Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="#">My Calendar</a></li>
                        <li><a href="#">My Calendar</a></li>
                    </ul>
                </li>

                <li class="has-sub-menu">
                    <a href="javascript:;">
                        <div class="icon-w"><i class="fas fa-address-card"></i></div>
                        <span>Contact Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="{% url 'contact:list' %}">Contacts</a></li>
                        <li><a href="{% url 'core:unit-list' %}">Unit</a></li>
                        <li><a href="{% url 'core:building-list' %}">Building</a></li>
                        <li><a href="{% url 'core:portfolio-list' %}">Portfolio</a></li>
                        <li><a href="{% url 'core:owner-group-list' %}">Owner Group</a></li>
                        <li><a href="{% url 'core:company-list' %}">Company</a></li>
                        <li><a href="{% url 'core:building-utility-list' %}">Utility</a></li>
                        <li><a href="{% url 'contact:service-type-list' %}">Service Type</a></li>
{#                        <li><a href="{% url 'contact:phone-type-list' %}">Phone Type</a></li>#}
                        <li><a href="{% url 'core:unit-appliance-type-list' %}">Appliance Type</a></li>
{#                        <li><a href="{% url 'core:program-list' %}">Program</a></li>#}
                    </ul>
                </li>

                <li class="sub-header">
                    <span>Options</span>
                </li>


                <li class="has-sub-menu">
{#                    <a href="{% url 'comm:index' %}">#}
                    <a href="{% url 'comm:inbox-messages' %}">
                        <div class="icon-w"><i class="fas fa-comment-smile"></i></div>
                        <span>Communication Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="{% url 'comm:inbox-messages' %}">Communication</a></li>
                    </ul>
                </li>
                <li class="has-sub-menu">
                        <div class="icon-w"><i class="fas fa-book"></i></div>
                        <span>Process Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="#">Manage TaskLists</a></li>
                        <li><a href="#">Manage Templates</a></li>
                    </ul>
                </li>
                <li class="has-sub-menu">
                    <a href="{% url 'success:index' %}">
                        <div class="icon-w"><i class="fas fa-chart-bar"></i></div>
                        <span>Success Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="#">Success</a></li>
                    </ul>
                </li>
                <li class="has-sub-menu">
                    <a href="{% url 'lease:index' %}">
                        <div class="icon-w"><i class="fas fa-key"></i></div>
                        <span>Lead Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="{% url 'lease:index' %}">Lead</a></li>
                    </ul>
                </li>
                <li class="has-sub-menu">
                    <a href="{% url 'team:index' %}">
                        <div class="icon-w"><i class="fas fa-heart"></i></div>
                        <span>Team Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="#">Team</a></li>
                    </ul>
                </li>
                <li class="has-sub-menu">
                    <a href="{% url 'accounting:index' %}">
                        <div class="icon-w"><i class="fas fa-dollar-sign"></i></div>
                        <span>Accounting Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="#">Accounting</a></li>
                    </ul>
                </li>
                <li class="has-sub-menu">
                    <a href="{% url 'maintenance:index' %}">
                        <div class="icon-w"><i class="fas fa-wrench"></i></div>
                        <span>Maintenance Manager</span>
                    </a>
                    <ul class="sub-menu">
                        <li><a href="#">Maintenance</a></li>
                    </ul>
                </li>

            </ul>
        {% endif %}
        <!--------------------
        END - Mobile Menu List
        -------------------->
        <div class="mobile-menu-magic">
            <h4>SavvyBiz</h4>
            <p>You are better served on the Mobile App</p>
            <div class="btn-w">
                <a class="btn btn-white btn-rounded" href="javascript:;" target="_blank">Download Now</a>
            </div>
        </div>
    </div>
</div>
<!--------------------
END - Mobile Menu
-------------------->

<!--------------------
START - Main Menu
-------------------->
<div class="menu-w color-scheme-dark color-style-bright menu-position-side menu-side-left menu-layout-compact sub-menu-style-over sub-menu-color-bright selected-menu-color-light menu-activated-on-hover menu-has-selected-link" style="min-height: 100vh;">
    <div class="logo-w_">
        <a class="logo" href="{% url 'core:index' %}">
            <img src="{% static 'img/SavvyBiz-logo.png' %}"><span></span>
            <div class="logo-label"></div>
        </a>
    </div>

    <h1 class="menu-page-header">Page Header</h1>

    {% if request.user.is_authenticated %}
        <ul class="main-menu">
            <li class="sub-header"><span>On Progress</span></li>

            <li class="sub-menu">
                <a href="{% url 'core:dashboard' %}">
                    <div class="icon-w"><i class="fas fa-home"></i></div>
                    <span>Home</span>
                </a>
            </li>
        </ul>
    {% endif %}

</div>
<!--------------------
END - Main Menu
-------------------->